### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by mkok1019**
Need to add installation steps.

### CODE REVIEW

**Comment by mkok1019** [comment]
@atcoco Hey, man.

I am not sure how to use this rjs package. Do you know how to install this?

**Comment by atcoco** [comment]
Hey @mkok1019 
I'm not very familiar with this package.

**Comment by mkok1019** [comment]
@atcoco Hmm... You can go through the README. Are you comfortable now? What is the best way to talk with you?

**Comment by atcoco** [comment]
I think, it is difficult now before I mentioned. I think, this method is best way and If I have good idea, I will leave message here and I haven't yet read the file

**Comment by mkok1019** [comment]
@atcoco ok, be careful with your back and sleep much, no need to work hard, parents are worrying about you, i will deliver your message to home. i may go home on December, 
I sent $ and mom's necklace to home today. if i have a chance, i will invite you to the project.
no my friend called me in home? my phone.

**Comment by atcoco** [comment]
our team check all thing, you must clear the commits and we discuss every monday. And a girl who knows you

**Comment by mkok1019** [comment]
Ok, I see. What is the name?

**Comment by atcoco** [comment]
I don't know

**Comment by mkok1019** [comment]
can anyone help this?

**Comment by atcoco** [comment]
What's this?

**Comment by mkok1019** [comment]
How is your business going?

**Comment by atcoco** [comment]
my aaccound (andrey Tuhel on upwor

**Comment by mkok1019** [comment]
I will not search it because its not a good activity.

**Comment by atcoco** [comment]
vladivostok

**Comment by mkok1019** [comment]
Yes, I mean I will not search yours because it is not a good activity for you. How much until now?
Do you know 2555290 or else?

**Comment by atcoco** [comment]
oh bro, my email is connected with my boss phone, so you must not use this email, I have to block you. And after I make a new mail, and then, I will contact to you again
  it's dangerous activity with me

**Pull request closed without merging**
